### ISSUE TITLE
Sandra Blow image text 

### ISSUE THREAD

**Issue by ftloa-altonwebsites** [altonwebsites/altonwebsites_ftloa#17]
Text same as borderline except it is numbered 53/75 and the year is 2000.

**Comment by altonwebsites** [comment]
Text changed as requested. Please confirm and close after next upoad to demo site.

**Comment by ftloa-altonwebsites** [comment]
text is ok but can you change the image to the correct one?  I think I emailed it to you the other day!

**Comment by altonwebsites** [comment]
Sorry, I thought I had. They're really similar! : )
Done now. WIll upload with the changes this evening

**Comment by ftloa-altonwebsites** [comment]
ah you have changed the wrong one.  the orange image is a Terry Frost! squares in orbit is the image you have changed Borderline to.  Borderline as it was was the correct image!   Also, I wanted to leave the 2 Sandra blows and the Wilhelmina Barns Graham blue light blue summer on the Featured St Ives pages (sorry if you missed this, I know I typed it somewhere, probably on a covering email) and I would like to use the blue light blue summer image as the lead image on the Featured page and also on the home page.  can you put them back in?

**Comment by altonwebsites** [comment]
Done. I think!
